site_name: Pampa Labs Blog
site_author: Pampa Labs
site_description: >-
  Insights and solutions for LLM technologies by Pampa Labs.
repo_name: pampa-labs-blog
repo_url: https://github.com/pampa-labs/pampa-labs.github.io
site_url: https://www.pampa.ai/
edit_uri: edit/main/docs/
copyright: Copyright &copy; 2024 Pampa Labs

theme:
  name: material
  logo: assets/pampa-labs.png
  favicon: assets/pampa-labs.png
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil 
    view: material/eye
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.tabs.link
    - content.tooltips
    - header.autohide
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.prune
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  palette:
      - scheme: default 
        primary: black 
        accent: indigo
        toggle:
          icon: material/brightness-7
          name: Switch to dark mode
      - scheme: slate
        primary: black
        accent: indigo
        toggle:
          icon: material/brightness-4
          name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
markdown_extensions:
  - abbr
  - admonition
  - pymdownx.details
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/mkdocs.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.arithmatex:
      generic: true
nav:
  - Home: index.md
  - Technical Writings:
    - "technical-writings/index.md"

plugins:
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
        minify_html: true
  - mkdocstrings:
      handlers:
        python:
          options:
            members_order: alphabetical
            allow_inspection: true
            show_bases: true
  - blog:
      blog_dir: technical-writings
      post_dir: technical-writings/posts
      post_date_format: full
      post_url_format: "{date}/{slug}"
      authors_file: ".authors.yml"
      blog_toc: true
      archive: true
      categories: false
      post_excerpt: required
      post_excerpt_separator: <!-- more -->
      post_readtime: true
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://x.com/pampalabs_
    - icon: fontawesome/brands/github
      link: https://github.com/pampa-labs
  analytics:
    provider: google
    property: G-SE5F8X8GK0
    feedback:
      title: Was this article helpful?
      ratings:
        - icon: material/thumb-up-outline
          name: This article was helpful
          data: 1
          note: >-
            Thanks for your feedback! We're glad you found this article useful.
        - icon: material/thumb-down-outline
          name: This article could be improved
          data: 0
          note: >- 
            Thanks for your feedback! We'd love to hear how we can improve this article.

