 authors:
  fpingham:
    name: Francisco Ingham
    description: Creator
    avatar: https://avatars.githubusercontent.com/u/24279597?v=4
  lpetralli:
    name: Lucas Petralli
    description: Creator
    avatar: https://avatars.githubusercontent.com/u/123559656?v=4
  lgesuellip:
    name: Lautaro Gesuelli Pinto
    description: Creator
    avatar: https://avatars.githubusercontent.com/u/102637283?v=4
    url: https://www.linkedin.com/in/lgesuellip/